### ISSUE TITLE
code about impulse initialization

### ISSUE THREAD

**Issue by jzyxn** [osiriszjq/impulse_init#1]
Could you share us with the code about how to get the random impulse convolution filters in Vit?

**Comment by osiriszjq** [comment]
Sure! You can check [vit.py](https://github.com/osiriszjq/impulse_init/blob/main/vit.py) in this repo or you can check the [colab](https://github.com/osiriszjq/impulse_init/blob/main/Impulse_Initialization.ipynb) for a [Simple ViT](https://arxiv.org/pdf/2205.01580.pdf) version. I'm working on integrating our method into normal vit in [timm framework](https://github.com/huggingface/pytorch-image-models/tree/main).

**Comment by jzyxn** [comment]
> Sure! You can check [vit.py](https://github.com/osiriszjq/impulse_init/blob/main/vit.py) in this repo or you can check the [colab](https://github.com/osiriszjq/impulse_init/blob/main/Impulse_Initialization.ipynb) for a [Simple ViT](https://arxiv.org/pdf/2205.01580.pdf) version. I'm working on integrating our method into normal vit in [timm framework](https://github.com/huggingface/pytorch-image-models/tree/main).

OK，thanks for your reply. I looked at it so fast that I thought you hadn't given. Thanks for pointing that out.

**Comment by jzyxn** [comment]
! [image](https://github.com/osiriszjq/impulse_init/assets/76219656/22a07088-a615-47ca-b322-1aa15e6fb3d8) 
An error occurred when running function "impulse_init".

**Comment by jzyxn** [comment]
![Quicker_20240130_174953](https://github.com/osiriszjq/impulse_init/assets/76219656/3ead1c47-0764-4661-89e3-ea2fc0bbad23)
An error occurred when running function "impulse_init".

**Comment by osiriszjq** [comment]
I did find some typos in the code and updated them, but I didn't see your error. How did you get this? `spatial_pe` here should be the positional encoding matrix, instead of just a bool flag.

**Comment by jzyxn** [comment]
I took the code in 'impulse_init' and ran it separately and didn't realise that the parameter spatial_pe in Transformer uses self.pos_embedding.Thanks for pointing that out.
